### ISSUE TITLE
Provide poseidon URL and port as environment variable or config option

### ISSUE THREAD

**Issue by rashley-iqt** [CyberReboot/CRviz#251]
### Describe the feature you are requesting
The current mechanism that CRviz uses to setup the url and port of the Poseidon Datasource is brittle and awkward. It would be ice to be able to pass the URL and port in to CRviz as opposed to calculating it.  

### Describe your use case
the current mechanism only works when the poseidon API is running on the same host as CRviz and 1 port down.

**Comment by cglewis** [comment]
Related, having the ability to connect to Poseidon from the server side rather than just from the browser. For example, Grafana let's you doing this when connecting datasources. This would allow the API to be exposed to only the server running CRviz as opposed to any user's machines using CRviz, as it currently does.
