### ISSUE TITLE
ability to have breadcrumb/shareable URLs

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/CRviz#50]
It would be nice if the URL add breadcrumbs when elements are changed in the control panel, so that someone could use the URL to get all of their particular settings back without having to click through all of them in the interface every time.

**Comment by rashley-iqt** [comment]
I've been thinking my way through this and I don't think a URL string is the way to do this.  The problem is basically that for a shareable URL to work in the expected fashion here we have to know the exact dataset and its exact state at the moment of sharing.  That could easily be too big into a URL so now we have to store that dataset somewhere that it can be retrieved based off of a URL which
- creates another component for us to maintain
- breaks what i think is one of our best features, no server setup
- invites all sorts of data ownership/retention headaches

It would essentially require us to rearchitect the whole system.  To that end, I propose that instead we wrap the whole thing up with our existing plans to augement the export functionality.  We already allow users to upload a datafile so if we expand that to include allowing that file to dictate control states and augment the download capability so that a user can choose to export:
- just data
- just control state
- data and control state

then we have a neat way of letting people "save" useful or interesting datasets and views without adding undue overhead.
